/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * This software is governed by the Broadcom Switch APIs license.
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#include <cdk/chip/bcm56340_a0_defs.h>

/* Block types */
const char *bcm56340_a0_blktype_names[] = {
    "axp",
    "cmic",
    "epipe",
    "ibod",
    "ipipe",
    "iproc",
    "ism",
    "mmu",
    "ser",
    "top",
    "xlport",
    "xtport",
    "xwport"
};

/* Block structures */
cdk_xgsm_block_t bcm56340_a0_blocks[] = 
{
    { BCM56340_A0_BLKTYPE_XLPORT,       12,   0,   CDK_PBMP_2(0x00000000, 0x001e0000) },
    { BCM56340_A0_BLKTYPE_XTPORT,        8,   0,   CDK_PBMP_1(0x00001ffe) },
    { BCM56340_A0_BLKTYPE_XTPORT,        9,   0,   CDK_PBMP_1(0x01ffe000) },
    { BCM56340_A0_BLKTYPE_XTPORT,       10,   0,   CDK_PBMP_2(0xfe000000, 0x0000001f) },
    { BCM56340_A0_BLKTYPE_XTPORT,       11,   0,   CDK_PBMP_2(0x00000000, 0x0001ffe0) },
    { BCM56340_A0_BLKTYPE_XWPORT,       13,   0,   CDK_PBMP_2(0x00000000, 0x01e00000) },
    { BCM56340_A0_BLKTYPE_XWPORT,       14,   0,   CDK_PBMP_2(0x00000000, 0x1e000000) },
    { BCM56340_A0_BLKTYPE_XWPORT,       15,   0,   CDK_PBMP_3(0x00000000, 0xe0000000, 0x00000001) },
    { BCM56340_A0_BLKTYPE_IPIPE,         1,   1,   CDK_PBMP_2(0xffffffff, 0x7fffffff) },
    { BCM56340_A0_BLKTYPE_EPIPE,         2,   1,   CDK_PBMP_2(0xffffffff, 0x7fffffff) },
    { BCM56340_A0_BLKTYPE_MMU,           3,   2,   CDK_PBMP_2(0xffffffff, 0x7fffffff) },
    { BCM56340_A0_BLKTYPE_AXP,           4,   0,   CDK_PBMP_3(0x00000000, 0x00000000, 0x003e0000) },
    { BCM56340_A0_BLKTYPE_TOP,           6,   0,   CDK_PBMP_3(0xffffffff, 0xffffffff, 0x003e0001) },
    { BCM56340_A0_BLKTYPE_ISM,          16,   1,   CDK_PBMP_2(0xffffffff, 0x7fffffff) },
    { BCM56340_A0_BLKTYPE_SER,          17,   0,   CDK_PBMP_3(0xffffffff, 0xffffffff, 0x003e0001) },
    { BCM56340_A0_BLKTYPE_IBOD,         18,   0,   CDK_PBMP_3(0xffffffff, 0xffffffff, 0x003e0001) },
    { BCM56340_A0_BLKTYPE_IPROC,        19,   0,   CDK_PBMP_3(0xffffffff, 0xffffffff, 0x003e0001) }
};

/* Symbol table */
#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
extern cdk_symbols_t bcm56340_a0_dsymbols;
#else
extern cdk_symbols_t bcm56340_a0_symbols;
#endif
#endif

/* Physical port numbers */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
static cdk_port_map_port_t _ports[] = {
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 49
};
#endif

/* Index ranges for this chip */
static cdk_xgsm_numel_range_t _numel_ranges[] = {
    {  0,  0, CDK_PBMP_2(0xffffffff, 0x77ffffff)             }, /*  0 */
    {  0,  9, CDK_PBMP_2(0x00000000, 0x0000ff00)             }, /*  1 */
    {  0,  7, CDK_PBMP_2(0x00000000, 0x0000000f)             }, /*  2 */
    {  0,  7, CDK_PBMP_2(0x00000000, 0x000000f0)             }, /*  3 */
    {  0,  9, CDK_PBMP_2(0x00000000, 0x00ff0000)             }, /*  4 */
    {  0,  7, CDK_PBMP_2(0x00000000, 0x01000000)             }, /*  5 */
    {  0, 47, CDK_PBMP_2(0x00000000, 0x08000000)             }, /*  6 */
    {  0,  7, CDK_PBMP_2(0x00000000, 0x04000000)             }, /*  7 */
    {  0,  0, CDK_PBMP_2(0xffffffff, 0x7dffffff)             }, /*  8 */
    {  0,  3, CDK_PBMP_2(0xffffffff, 0x7dffffff)             }, /*  9 */
    {  1,  7, CDK_PBMP_2(0xffffffff, 0x1dffffff)             }, /* 10 */
    {  8,  9, CDK_PBMP_2(0x00000000, 0x08ffff00)             }, /* 11 */
    { 10, 47, CDK_PBMP_2(0x00000000, 0x08000000)             }, /* 12 */
    {  0,  0, CDK_PBMP_2(0xffffffff, 0x3dffffff)             }, /* 13 */
    {  0,  0, CDK_PBMP_2(0xffffffff, 0x35ffffff)             }  /* 14 */
};

/* Register array encodings for this chip */
static cdk_xgsm_numel_encoding_t _numel_encodings[] = {
    { { 14 } },
    { {  0, -1 } },
    { {  1, -1 } },
    { {  2, -1 } },
    { {  3, -1 } },
    { {  4, -1 } },
    { {  5, -1 } },
    { {  6, -1 } },
    { {  7, -1 } },
    { {  8, -1 } },
    { {  9, -1 } },
    { {  8, 10, 11, 12, -1 } },
    { { 13, 10, 11, 12, -1 } },
    { { 14, -1 } }
};

/* Variable register array info */
cdk_xgsm_numel_info_t bcm56340_a0_numel_info = {
    _numel_ranges,
    _numel_encodings
};

/* Chip information structure */
static cdk_xgsm_chip_info_t bcm56340_a0_chip_info = {

    /* CMIC block */
    BCM56340_A0_CMIC_BLOCK,

    /* CMC instance */
    0,

    /* Other (non-CMIC) block types */
    13,
    bcm56340_a0_blktype_names,

    /* Address calculation */
    NULL,

    /* Other (non-CMIC) blocks */
    17,
    bcm56340_a0_blocks,

    /* Valid ports for this chip */
    CDK_PBMP_3(0xffffffff, 0xffe3ffff, 0x00000001),

    /* Chip flags */
    CDK_XGSM_CHIP_FLAG_IPROC |
    BCM56340_A0_CHIP_FLAG_BW150G |
    0,

#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
    /* Use regenerated symbol tables from the DSYM program */
    &bcm56340_a0_dsymbols,
#else
    /* Use the static per-chip symbol tables */
    &bcm56340_a0_symbols,
#endif
#endif

    /* Port map */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
    sizeof(_ports)/sizeof(_ports[0]),
    _ports,
#endif

    /* Variable register array info */
    &bcm56340_a0_numel_info,

    /* Configuration dependent memory max index */
    NULL,

};

/* Declare function first to prevent compiler warnings */
extern int
bcm56340_a0_setup(cdk_dev_t *dev);

int
bcm56340_a0_setup(cdk_dev_t *dev)
{
    dev->chip_info = &bcm56340_a0_chip_info;

    return cdk_xgsm_setup(dev);
}

