# $Id: f6a72f499f7e00c5b2630bd7cb328e7d29acae64 $ Broadcom SDK $
# This software is governed by the Broadcom Switch APIs license.
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = generic
LIBNAME = libphygeneric

include $(CDK)/make/lib.mk
