/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * This software is governed by the Broadcom Switch APIs license.
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#include <cdk/chip/bcm56334_b0_defs.h>

/* Block types */
extern const char *bcm56334_b0_blktype_names[];

/* Block structures */
extern cdk_xgs_block_t bcm56334_b0_blocks[];

/* Symbol table */
#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
extern cdk_symbols_t bcm56334_b0_dsymbols;
#else
extern cdk_symbols_t bcm56334_b0_symbols;
#endif
#endif

/* Physical port numbers */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
static cdk_port_map_port_t _ports[] = {
    0, 2, 3, 4, 5, 6, 7
};
#endif

/* Chip-specific memory sizes */
static uint32_t
bcm56334_b0_mem_maxidx(uint32_t addr, uint32_t maxidx)
{
    switch (addr) {
    case EGR_MPLS_VC_AND_SWAP_LABEL_TABLEm:
    case L3_DEFIPm:
    case L3_DEFIP_DATA_ONLYm:
    case L3_DEFIP_HIT_ONLYm:
    case L3_DEFIP_ONLYm:
    case MPLS_ENTRYm:
    case VFIm:
    case VFI_1m:
        return 1023; /* 0x3ff */
    case L2Xm:
    case L2_ENTRY_ONLYm:
        return 16383; /* 0x3fff */
    case EGR_L3_NEXT_HOPm:
    case ING_L3_NEXT_HOPm:
    case INITIAL_ING_L3_NEXT_HOPm:
    case L2_HITDA_ONLYm:
    case L2_HITSA_ONLYm:
        return 2047; /* 0x7ff */
    case EGR_IP_TUNNEL_MPLSm:
        return 255; /* 0xff */
    case ING_DVP_TABLEm:
    case SOURCE_VPm:
    case SVP_DISABLE_VLAN_CHECKS_TABm:
        return 4095; /* 0xfff */
    case EGR_IPMCm:
    case L3_IPMCm:
    case MMU_IPMC_GROUP_TBL0m:
    case MMU_IPMC_GROUP_TBL1m:
    case MMU_IPMC_GROUP_TBL2m:
    case MMU_IPMC_GROUP_TBL3m:
        return 511; /* 0x1ff */
    case VLAN_OR_VFI_MAC_COUNTm:
    case VLAN_OR_VFI_MAC_LIMITm:
        return 5119; /* 0x13ff */
    case L3_MTU_VALUESm:
        return 8703; /* 0x21ff */
    }
    return maxidx;
}

/* Variable register array info */
extern cdk_xgs_numel_info_t bcm56334_b0_numel_info;

/* Chip information structure */
static cdk_xgs_chip_info_t bcm56231_b0_chip_info = {

    /* CMIC block */
    BCM56334_B0_CMIC_BLOCK,

    /* Other (non-CMIC) block types */
    6,
    bcm56334_b0_blktype_names,

    /* Address calculation */
    NULL,

    /* Other (non-CMIC) blocks */
    10,
    bcm56334_b0_blocks,

    /* Valid ports for this chip */
    CDK_PBMP_1(0x000000fd),

    /* Chip flags */
    CDK_XGS_CHIP_FLAG_CLAUSE45 |
    CDK_XGS_CHIP_FLAG_SCHAN_EXT |
    0,

#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
    /* Use regenerated symbol tables from the DSYM program */
    &bcm56334_b0_dsymbols,
#else
    /* Use the static per-chip symbol tables */
    &bcm56334_b0_symbols,
#endif
#endif

    /* Port map */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
    sizeof(_ports)/sizeof(_ports[0]),
    _ports,
#endif

    /* Variable register array info */
    &bcm56334_b0_numel_info,

    /* Configuration dependent memory max index */
    &bcm56334_b0_mem_maxidx,

};

/* Declare function first to prevent compiler warnings */
extern int
bcm56231_b0_setup(cdk_dev_t *dev);

int
bcm56231_b0_setup(cdk_dev_t *dev)
{
    dev->chip_info = &bcm56231_b0_chip_info;

    return cdk_xgs_setup(dev);
}

