#ifndef __PHYMOD_BCMI_TSCE_DPLL_XGXS_H__
#define __PHYMOD_BCMI_TSCE_DPLL_XGXS_H__
/*******************************************************************************
 *
 * This software is governed by the Broadcom Switch APIs license.
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * Definition file for the BCMI_TSCE_XGXS.
 * This file provides all basic definitions required to program the BCMI_TSCE_XGXS.
 *
 * This file is autogenerated. Please do not edit.
 */

#include <phy/chip/bcmi_tsce_dpll_xgxs_defs.h>

#endif /* __PHYMOD_BCMI_TSCE_DPLL_XGXS_H__ */
