/*
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 * 
 * This software is governed by the Broadcom Switch APIs license.
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#ifndef __BMD_REMAP_H__
#define __BMD_REMAP_H__

#include <bmd_config.h>


/*******************************************************************************
 *
 * The following #defines allow remapping of the BMD API based on the value of 
 * BMD_CONFIG_API_PREFIX when it is defined. This will most often be used to
 * eliminate the intermediate API dispatch mechanism when not needed.
 */

#if defined(BMD_CONFIG_API_PREFIX) && !defined(BMD_CONFIG_API_PREFIX_DISABLE)

#define __BMD_API_CONCAT(x,y) x##y
#define _BMD_API_CONCAT(x,y) __BMD_API_CONCAT(x,y)

#define bmd_attach _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_attach)
#define bmd_detach _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_detach)
#define bmd_reset _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_reset)
#define bmd_init _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_init)
#define bmd_port_mode_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_mode_set)
#define bmd_port_mode_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_mode_get)
#define bmd_port_mode_update _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_mode_update)
#define bmd_vlan_create _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_vlan_create)
#define bmd_vlan_port_add _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_vlan_port_add)
#define bmd_vlan_port_remove _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_vlan_port_remove)
#define bmd_vlan_port_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_vlan_port_get)
#define bmd_vlan_destroy _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_vlan_destroy)
#define bmd_port_vlan_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_vlan_set)
#define bmd_port_vlan_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_vlan_get)
#define bmd_port_stp_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_stp_set)
#define bmd_port_stp_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_stp_get)
#define bmd_switching_init _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_switching_init)
#define bmd_port_mac_addr_add _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_mac_addr_add)
#define bmd_port_mac_addr_remove _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_mac_addr_remove)
#define bmd_cpu_mac_addr_add _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cpu_mac_addr_add)
#define bmd_cpu_mac_addr_remove _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cpu_mac_addr_remove)
#define bmd_tx _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_tx)
#define bmd_rx_start _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_rx_start)
#define bmd_rx_poll _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_rx_poll)
#define bmd_rx_stop _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_rx_stop)
#define bmd_stat_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_stat_get)
#define bmd_stat_clear _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_stat_clear)
#define bmd_test_interrupt_assert _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_test_interrupt_assert)
#define bmd_test_interrupt_clear _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_test_interrupt_clear)
#define bmd_download _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_download)

#endif /* BMD_CONFIG_API_PREFIX */

#endif /* __BMD_REMAP_H__ */
