# $Id: afc4a5e17a9193a364d72ef06765da925ce6ea49 $ Broadcom SDK $
# This software is governed by the Broadcom Switch APIs license.
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = main
LIBNAME = libcdkmain

include $(CDK)/make/lib.mk
