# $Id: 04bd07e16d552d55f61316ed093ccd3c66bb0580 $ Broadcom SDK $
# This software is governed by the Broadcom Switch APIs license.
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = shared
LIBNAME = libbdeshared

include $(CDK)/make/lib.mk
