/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * This software is governed by the Broadcom Switch APIs license.
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#include <cdk/chip/bcm88230_a0_defs.h>

/* Block types */
const char *bcm88230_a0_blktype_names[] = {
    "bp",
    "ci",
    "cmic",
    "cs",
    "eb",
    "ep",
    "es",
    "fd",
    "ff",
    "fr",
    "gxport",
    "qma",
    "qmb",
    "qmc",
    "qsa",
    "qsb",
    "rb",
    "sc_top",
    "sf_top",
    "ts",
    "tx"
};

/* Block structures */
cdk_xgs_block_t bcm88230_a0_blocks[] = 
{
    { BCM88230_A0_BLKTYPE_GXPORT,       30,     CDK_PBMP_1(0x00000002) },
    { BCM88230_A0_BLKTYPE_GXPORT,       31,     CDK_PBMP_1(0x00000004) },
    { BCM88230_A0_BLKTYPE_GXPORT,       32,     CDK_PBMP_1(0x00000008) },
    { BCM88230_A0_BLKTYPE_GXPORT,       33,     CDK_PBMP_1(0x00000010) },
    { BCM88230_A0_BLKTYPE_GXPORT,       34,     CDK_PBMP_1(0x00000020) },
    { BCM88230_A0_BLKTYPE_GXPORT,       35,     CDK_PBMP_1(0x00000040) },
    { BCM88230_A0_BLKTYPE_GXPORT,       36,     CDK_PBMP_1(0x00000080) },
    { BCM88230_A0_BLKTYPE_GXPORT,       37,     CDK_PBMP_1(0x00000100) },
    { BCM88230_A0_BLKTYPE_BP,           0,      CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_CI,           1,      CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_CI,           2,      CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_CI,           3,      CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_CI,           4,      CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_CI,           5,      CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_CI,           6,      CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_CI,           7,      CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_CI,           8,      CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_CI,           9,      CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_CI,           10,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_CS,           12,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_EB,           13,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_EP,           14,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_ES,           15,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_FD,           16,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_FF,           17,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_FR,           18,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_QMA,          20,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_QMB,          21,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_QMC,          22,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_QSA,          23,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_QSB,          24,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_RB,           25,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_SC_TOP,       26,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_SF_TOP,       27,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_TS,           28,     CDK_PBMP_1(0x000001ff) },
    { BCM88230_A0_BLKTYPE_TX,           29,     CDK_PBMP_1(0x000001ff) }
};

/* Symbol table */
#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
extern cdk_symbols_t bcm88230_a0_dsymbols;
#else
extern cdk_symbols_t bcm88230_a0_symbols;
#endif
#endif

/* Physical port numbers */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
static cdk_port_map_port_t _ports[] = {
    0, 1, 2, 3, 4, 5, 6, 7, 8
};
#endif

/* Declare function first to prevent compiler warnings */
extern uint32_t
bcm88230_a0_blockport_addr(int block, int port, uint32_t offset);

uint32_t
bcm88230_a0_blockport_addr(int block, int port, uint32_t offset)
{
    if (block & 0x10) {
        block &= ~0x10;
        block |= 0x400;
    }
    if (block & 0x20) {
        block &= ~0x20;
        block |= 0x800;
    }
    return ((block * 0x100000) | (port * 0x1000) | (offset & ~0xf00000)); 
}

/* Chip information structure */
static cdk_xgs_chip_info_t bcm88230_a0_chip_info = {

    /* CMIC block */
    BCM88230_A0_CMIC_BLOCK,

    /* Other (non-CMIC) block types */
    21,
    bcm88230_a0_blktype_names,

    /* Address calculation */
    bcm88230_a0_blockport_addr,

    /* Other (non-CMIC) blocks */
    36,
    bcm88230_a0_blocks,

    /* Valid ports for this chip */
    CDK_PBMP_1(0x000001ff),

    /* Chip flags */
    CDK_XGS_CHIP_FLAG_CLAUSE45 |
    CDK_XGS_CHIP_FLAG_SCHAN_EXT |
    CDK_XGS_CHIP_FLAG_SCHAN_SB0 |
    CDK_XGS_CHIP_FLAG_SCHAN_MBI |
    0,

#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
    /* Use regenerated symbol tables from the DSYM program */
    &bcm88230_a0_dsymbols,
#else
    /* Use the static per-chip symbol tables */
    &bcm88230_a0_symbols,
#endif
#endif

    /* Port map */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
    sizeof(_ports)/sizeof(_ports[0]),
    _ports,
#endif

    /* Variable register array info */
    NULL,

    /* Configuration dependent memory max index */
    NULL,

};

/* Declare function first to prevent compiler warnings */
extern int
bcm88230_a0_setup(cdk_dev_t *dev);

int
bcm88230_a0_setup(cdk_dev_t *dev)
{
    dev->chip_info = &bcm88230_a0_chip_info;

    return cdk_xgs_setup(dev);
}

