/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * This software is governed by the Broadcom Switch APIs license.
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#include <cdk/chip/bcm56334_a0_defs.h>

/* Block types */
const char *bcm56334_a0_blktype_names[] = {
    "cmic",
    "epipe",
    "gport",
    "ipipe",
    "mmu",
    "xqport"
};

/* Block structures */
cdk_xgs_block_t bcm56334_a0_blocks[] = 
{
    { BCM56334_A0_BLKTYPE_GPORT,        2,      CDK_PBMP_1(0x000003fc) },
    { BCM56334_A0_BLKTYPE_GPORT,        3,      CDK_PBMP_1(0x0003fc00) },
    { BCM56334_A0_BLKTYPE_GPORT,        4,      CDK_PBMP_1(0x03fc0000) },
    { BCM56334_A0_BLKTYPE_XQPORT,       5,      CDK_PBMP_1(0x04000000) },
    { BCM56334_A0_BLKTYPE_XQPORT,       6,      CDK_PBMP_1(0x08000000) },
    { BCM56334_A0_BLKTYPE_XQPORT,       7,      CDK_PBMP_1(0x10000000) },
    { BCM56334_A0_BLKTYPE_XQPORT,       8,      CDK_PBMP_1(0x20000000) },
    { BCM56334_A0_BLKTYPE_IPIPE,        10,     CDK_PBMP_1(0x3fffffff) },
    { BCM56334_A0_BLKTYPE_EPIPE,        11,     CDK_PBMP_1(0x3fffffff) },
    { BCM56334_A0_BLKTYPE_MMU,          12,     CDK_PBMP_1(0x3fffffff) }
};

/* Symbol table */
#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
extern cdk_symbols_t bcm56334_a0_dsymbols;
#else
extern cdk_symbols_t bcm56334_a0_symbols;
#endif
#endif

/* Physical port numbers */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
static cdk_port_map_port_t _ports[] = {
    0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
};
#endif

/* Index ranges for this chip */
static cdk_xgs_numel_range_t _numel_ranges[] = {
    {  0,  0, CDK_PBMP_1(0x3ffffffc)                         }, /*  0 */
    {  0,  7, CDK_PBMP_1(0x3ffffffd)                         }, /*  1 */
    {  8,  9, CDK_PBMP_1(0x3c000001)                         }, /*  2 */
    { 10, 47, CDK_PBMP_1(0x00000001)                         }, /*  3 */
    {  0,  0, CDK_PBMP_1(0x3c000000)                         }, /*  4 */
    {  8, 23, CDK_PBMP_1(0x3c000001)                         }, /*  5 */
    { 24, 47, CDK_PBMP_1(0x00000001)                         }, /*  6 */
    {  0,  0, CDK_PBMP_1(0x3c000001)                         }, /*  7 */
    {  0,  7, CDK_PBMP_1(0x3ffffffc)                         }, /*  8 */
    {  8, 25, CDK_PBMP_1(0x3c000000)                         }, /*  9 */
    {  0,  0, CDK_PBMP_1(0x3ffffffd)                         }, /* 10 */
    {  1,  7, CDK_PBMP_1(0x3c000000)                         }, /* 11 */
    {  0, 15, CDK_PBMP_1(0x3c000000)                         }, /* 12 */
    {  8, 23, CDK_PBMP_1(0x3c000000)                         }  /* 13 */
};

/* Register array encodings for this chip */
static cdk_xgs_numel_encoding_t _numel_encodings[] = {
    { { 10 } },
    { {  0, -1 } },
    { {  1,  2,  3, -1 } },
    { {  4, -1 } },
    { {  1,  5,  6, -1 } },
    { {  7, -1 } },
    { {  8,  9, -1 } },
    { { 10, 11, -1 } },
    { { 12, -1 } },
    { {  8, 13, -1 } }
};

/* Variable register array info */
cdk_xgs_numel_info_t bcm56334_a0_numel_info = {
    _numel_ranges,
    _numel_encodings
};

/* Chip information structure */
static cdk_xgs_chip_info_t bcm56334_a0_chip_info = {

    /* CMIC block */
    BCM56334_A0_CMIC_BLOCK,

    /* Other (non-CMIC) block types */
    6,
    bcm56334_a0_blktype_names,

    /* Address calculation */
    NULL,

    /* Other (non-CMIC) blocks */
    10,
    bcm56334_a0_blocks,

    /* Valid ports for this chip */
    CDK_PBMP_1(0x3ffffffd),

    /* Chip flags */
    CDK_XGS_CHIP_FLAG_CLAUSE45 |
    CDK_XGS_CHIP_FLAG_SCHAN_EXT |
    0,

#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
    /* Use regenerated symbol tables from the DSYM program */
    &bcm56334_a0_dsymbols,
#else
    /* Use the static per-chip symbol tables */
    &bcm56334_a0_symbols,
#endif
#endif

    /* Port map */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
    sizeof(_ports)/sizeof(_ports[0]),
    _ports,
#endif

    /* Variable register array info */
    &bcm56334_a0_numel_info,

    /* Configuration dependent memory max index */
    NULL,

};

/* Declare function first to prevent compiler warnings */
extern int
bcm56334_a0_setup(cdk_dev_t *dev);

int
bcm56334_a0_setup(cdk_dev_t *dev)
{
    dev->chip_info = &bcm56334_a0_chip_info;

    return cdk_xgs_setup(dev);
}

