# $Id: c59be0ab6e16267236e023541d59fe3ee479a9a0 $ Broadcom SDK $
# This software is governed by the Broadcom Switch APIs license.
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = shell
LIBNAME = libbmdshell

include $(CDK)/make/lib.mk

