/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * This software is governed by the Broadcom Switch APIs license.
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#include <cdk/chip/bcm56640_a0_defs.h>

/* Block types */
extern const char *bcm56640_a0_blktype_names[];

/* Block structures */
extern cdk_xgsm_block_t bcm56640_a0_blocks[];

/* Symbol table */
#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
extern cdk_symbols_t bcm56640_a0_dsymbols;
#else
extern cdk_symbols_t bcm56640_a0_symbols;
#endif
#endif

/* Physical port numbers */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
static cdk_port_map_port_t _ports[] = {
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 37, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 57, 58, 59, 60, 65, 69, 73, 77
};
#endif

/* Chip-specific memory sizes */
static uint32_t
bcm56640_a0_mem_maxidx(int enum_val, uint32_t maxidx)
{
    switch (enum_val) {
    case MPLS_ENTRYm_ENUM:
    case MPLS_ENTRY_HIT_ONLYm_ENUM:
    case VLAN_XLATEm_ENUM:
    case VLAN_XLATE_HIT_ONLYm_ENUM:
        return 24575; /* 0x5fff */
    case EXT_L2_ENTRY_1m_ENUM:
    case EXT_L2_ENTRY_2m_ENUM:
    case EXT_L2_ENTRY_DATA_ONLYm_ENUM:
    case EXT_L2_ENTRY_DATA_ONLY_WIDEm_ENUM:
    case EXT_L2_ENTRY_TCAMm_ENUM:
    case EXT_TCAM_VBITm_ENUM:
        return 0; /* 0x0 */
    case MPLS_ENTRY_EXTDm_ENUM:
    case MPLS_ENTRY_EXTD_HIT_ONLYm_ENUM:
    case VLAN_XLATE_EXTDm_ENUM:
    case VLAN_XLATE_EXTD_HIT_ONLYm_ENUM:
        return 12287; /* 0x2fff */
    case L2_ENTRY_2m_ENUM:
    case L2_ENTRY_2_HIT_ONLYm_ENUM:
    case L3_ENTRY_2m_ENUM:
    case L3_ENTRY_2_HIT_ONLYm_ENUM:
        return 22527; /* 0x57ff */
    case L3_ENTRY_4m_ENUM:
    case L3_ENTRY_4_HIT_ONLYm_ENUM:
        return 11263; /* 0x2bff */
    case EGR_VLAN_XLATEm_ENUM:
    case EGR_VLAN_XLATE_HIT_ONLYm_ENUM:
    case L3_IPMCm_ENUM:
    case L3_IPMC_1m_ENUM:
    case L3_IPMC_REMAPm_ENUM:
    case MMU_REPL_GROUPm_ENUM:
        return 8191; /* 0x1fff */
    case ING_UNTAGGED_PHBm_ENUM:
        return 62; /* 0x3e */
    case L2_ENTRY_1m_ENUM:
    case L2_ENTRY_1_HIT_ONLYm_ENUM:
    case L3_ENTRY_1m_ENUM:
    case L3_ENTRY_1_HIT_ONLYm_ENUM:
        return 45055; /* 0xafff */
    }
    return maxidx;
}

/* Variable register array info */
extern cdk_xgsm_numel_info_t bcm56640_a0_numel_info;

/* Chip information structure */
static cdk_xgsm_chip_info_t bcm56648_a0_chip_info = {

    /* CMIC block */
    BCM56640_A0_CMIC_BLOCK,

    /* CMC instance */
    0,

    /* Other (non-CMIC) block types */
    12,
    bcm56640_a0_blktype_names,

    /* Address calculation */
    NULL,

    /* Other (non-CMIC) blocks */
    16,
    bcm56640_a0_blocks,

    /* Valid ports for this chip */
    CDK_PBMP_3(0xffffffff, 0x1e1ffe3f, 0x003e2222),

    /* Chip flags */
    BCM56640_A0_CHIP_FLAG_BW280G |
    0,

#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
    /* Use regenerated symbol tables from the DSYM program */
    &bcm56640_a0_dsymbols,
#else
    /* Use the static per-chip symbol tables */
    &bcm56640_a0_symbols,
#endif
#endif

    /* Port map */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
    sizeof(_ports)/sizeof(_ports[0]),
    _ports,
#endif

    /* Variable register array info */
    &bcm56640_a0_numel_info,

    /* Configuration dependent memory max index */
    &bcm56640_a0_mem_maxidx,

};

/* Declare function first to prevent compiler warnings */
extern int
bcm56648_a0_setup(cdk_dev_t *dev);

int
bcm56648_a0_setup(cdk_dev_t *dev)
{
    dev->chip_info = &bcm56648_a0_chip_info;

    return cdk_xgsm_setup(dev);
}

