# $Id: e45b943aa4912e0f0c06a8824d51a8f1eb31b4f8 $ Broadcom SDK $
# This software is governed by the Broadcom Switch APIs license.
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = shared
LIBNAME = libcdkshared

include $(CDK)/make/lib.mk
