/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * This software is governed by the Broadcom Switch APIs license.
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#include <cdk/chip/bcm56450_a0_defs.h>

/* Block types */
const char *bcm56450_a0_blktype_names[] = {
    "ci",
    "cmic",
    "epipe",
    "ipipe",
    "iproc",
    "lls",
    "mmu",
    "mxqport",
    "rxlp",
    "ser",
    "top",
    "txlp"
};

/* Block structures */
cdk_xgsm_block_t bcm56450_a0_blocks[] = 
{
    { BCM56450_A0_BLKTYPE_MXQPORT,       6,   0,   CDK_PBMP_1(0x0000001e) },
    { BCM56450_A0_BLKTYPE_MXQPORT,       7,   0,   CDK_PBMP_1(0x000001e0) },
    { BCM56450_A0_BLKTYPE_MXQPORT,       8,   0,   CDK_PBMP_1(0x00001e00) },
    { BCM56450_A0_BLKTYPE_MXQPORT,       9,   0,   CDK_PBMP_1(0x0001e000) },
    { BCM56450_A0_BLKTYPE_MXQPORT,      10,   0,   CDK_PBMP_1(0x001e0000) },
    { BCM56450_A0_BLKTYPE_MXQPORT,      11,   0,   CDK_PBMP_1(0x01e00000) },
    { BCM56450_A0_BLKTYPE_MXQPORT,      12,   0,   CDK_PBMP_2(0x02000000, 0x00000038) },
    { BCM56450_A0_BLKTYPE_MXQPORT,      13,   0,   CDK_PBMP_2(0x04000000, 0x000001c0) },
    { BCM56450_A0_BLKTYPE_MXQPORT,      14,   0,   CDK_PBMP_2(0x08000000, 0x00000007) },
    { BCM56450_A0_BLKTYPE_MXQPORT,      15,   0,   CDK_PBMP_1(0xf0000000) },
    { BCM56450_A0_BLKTYPE_MXQPORT,      29,   0,   CDK_PBMP_2(0x00000000, 0x00000400) },
    { BCM56450_A0_BLKTYPE_IPIPE,         1,   0,   CDK_PBMP_2(0xffffffff, 0x000003ff) },
    { BCM56450_A0_BLKTYPE_EPIPE,         2,   0,   CDK_PBMP_2(0xffffffff, 0x000003ff) },
    { BCM56450_A0_BLKTYPE_MMU,           3,   0,   CDK_PBMP_2(0xffffffff, 0x000003ff) },
    { BCM56450_A0_BLKTYPE_TOP,          16,   0,   CDK_PBMP_2(0xffffffff, 0x000007ff) },
    { BCM56450_A0_BLKTYPE_LLS,          17,   0,   CDK_PBMP_2(0xffffffff, 0x000007ff) },
    { BCM56450_A0_BLKTYPE_CI,           18,   0,   CDK_PBMP_2(0xffffffff, 0x000007ff) },
    { BCM56450_A0_BLKTYPE_CI,           19,   0,   CDK_PBMP_2(0xffffffff, 0x000007ff) },
    { BCM56450_A0_BLKTYPE_CI,           20,   0,   CDK_PBMP_2(0xffffffff, 0x000007ff) },
    { BCM56450_A0_BLKTYPE_CI,           21,   0,   CDK_PBMP_2(0xffffffff, 0x000007ff) },
    { BCM56450_A0_BLKTYPE_CI,           22,   0,   CDK_PBMP_2(0xffffffff, 0x000007ff) },
    { BCM56450_A0_BLKTYPE_CI,           23,   0,   CDK_PBMP_2(0xffffffff, 0x000007ff) },
    { BCM56450_A0_BLKTYPE_RXLP,         24,   0,   CDK_PBMP_1(0x0000000f) },
    { BCM56450_A0_BLKTYPE_RXLP,         25,   0,   CDK_PBMP_1(0x0000000f) },
    { BCM56450_A0_BLKTYPE_TXLP,         26,   0,   CDK_PBMP_1(0x0000000f) },
    { BCM56450_A0_BLKTYPE_TXLP,         27,   0,   CDK_PBMP_1(0x0000000f) },
    { BCM56450_A0_BLKTYPE_SER,          28,   0,   CDK_PBMP_2(0xffffffff, 0x000007ff) },
    { BCM56450_A0_BLKTYPE_IPROC,        30,   0,   CDK_PBMP_2(0xffffffff, 0x000007ff) }
};

/* Symbol table */
#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
extern cdk_symbols_t bcm56450_a0_dsymbols;
#else
extern cdk_symbols_t bcm56450_a0_symbols;
#endif
#endif

/* Physical port numbers */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
static cdk_port_map_port_t _ports[] = {
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42
};
#endif

/* Index ranges for this chip */
static cdk_xgsm_numel_range_t _numel_ranges[] = {
    {  0,  0, CDK_PBMP_2(0xfffffffe, 0x000003ff)             }, /*  0 */
    {  0,  0, CDK_PBMP_2(0xffffffff, 0x000007ff)             }, /*  1 */
    {  0,  0, CDK_PBMP_2(0xffffffff, 0x000003ff)             }, /*  2 */
    {  0,  0, CDK_PBMP_2(0xfe000001, 0x000003ff)             }, /*  3 */
    {  0,  0, CDK_PBMP_2(0xffffffff, 0x000001ff)             }, /*  4 */
    {  0, 11, CDK_PBMP_2(0xffffffff, 0x000007ff)             }  /*  5 */
};

/* Register array encodings for this chip */
static cdk_xgsm_numel_encoding_t _numel_encodings[] = {
    { { 7 } },
    { {  0, -1 } },
    { {  1, -1 } },
    { {  2, -1 } },
    { {  3, -1 } },
    { {  4, -1 } },
    { {  5, -1 } }
};

/* Variable register array info */
cdk_xgsm_numel_info_t bcm56450_a0_numel_info = {
    _numel_ranges,
    _numel_encodings
};

/* Chip information structure */
static cdk_xgsm_chip_info_t bcm56450_a0_chip_info = {

    /* CMIC block */
    BCM56450_A0_CMIC_BLOCK,

    /* CMC instance */
    0,

    /* Other (non-CMIC) block types */
    12,
    bcm56450_a0_blktype_names,

    /* Address calculation */
    NULL,

    /* Other (non-CMIC) blocks */
    28,
    bcm56450_a0_blocks,

    /* Valid ports for this chip */
    CDK_PBMP_2(0xffffffff, 0x000007ff),

    /* Chip flags */
    CDK_XGSM_CHIP_FLAG_IPROC |
    0,

#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
    /* Use regenerated symbol tables from the DSYM program */
    &bcm56450_a0_dsymbols,
#else
    /* Use the static per-chip symbol tables */
    &bcm56450_a0_symbols,
#endif
#endif

    /* Port map */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
    sizeof(_ports)/sizeof(_ports[0]),
    _ports,
#endif

    /* Variable register array info */
    &bcm56450_a0_numel_info,

    /* Configuration dependent memory max index */
    NULL,

};

/* Declare function first to prevent compiler warnings */
extern int
bcm56450_a0_setup(cdk_dev_t *dev);

int
bcm56450_a0_setup(cdk_dev_t *dev)
{
    dev->chip_info = &bcm56450_a0_chip_info;

    return cdk_xgsm_setup(dev);
}

