# $Id: 4c4007e1da92d82bd97213766fb27d97038d4c2f $ Broadcom SDK $
# This software is governed by the Broadcom Switch APIs license.
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = util
LIBNAME = libphyutil

include $(CDK)/make/lib.mk
