/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * This software is governed by the Broadcom Switch APIs license.
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#include <cdk/chip/bcm56334_a0_defs.h>

/* Block types */
extern const char *bcm56334_a0_blktype_names[];

/* Block structures */
extern cdk_xgs_block_t bcm56334_a0_blocks[];

/* Symbol table */
#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
extern cdk_symbols_t bcm56334_a0_dsymbols;
#else
extern cdk_symbols_t bcm56334_a0_symbols;
#endif
#endif

/* Physical port numbers */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
static cdk_port_map_port_t _ports[] = {
    0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
};
#endif

/* Chip-specific memory sizes */
static uint32_t
bcm56334_a0_mem_maxidx(uint32_t addr, uint32_t maxidx)
{
    switch (addr) {
    case EGR_MPLS_VC_AND_SWAP_LABEL_TABLEm:
    case MPLS_ENTRYm:
    case OAM_LM_COUNTERSm:
        return 0; /* 0x0 */
    case L2Xm:
    case L2_ENTRY_ONLYm:
        return 16383; /* 0x3fff */
    case L2_HITDA_ONLYm:
    case L2_HITSA_ONLYm:
        return 2047; /* 0x7ff */
    case L3_DEFIPm:
    case L3_DEFIP_DATA_ONLYm:
    case L3_DEFIP_HIT_ONLYm:
    case L3_DEFIP_ONLYm:
        return 511; /* 0x1ff */
    }
    return maxidx;
}

/* Variable register array info */
extern cdk_xgs_numel_info_t bcm56334_a0_numel_info;

/* Chip information structure */
static cdk_xgs_chip_info_t bcm56321_a0_chip_info = {

    /* CMIC block */
    BCM56334_A0_CMIC_BLOCK,

    /* Other (non-CMIC) block types */
    6,
    bcm56334_a0_blktype_names,

    /* Address calculation */
    NULL,

    /* Other (non-CMIC) blocks */
    10,
    bcm56334_a0_blocks,

    /* Valid ports for this chip */
    CDK_PBMP_1(0x3ffffffd),

    /* Chip flags */
    CDK_XGS_CHIP_FLAG_CLAUSE45 |
    CDK_XGS_CHIP_FLAG_SCHAN_EXT |
    0,

#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
    /* Use regenerated symbol tables from the DSYM program */
    &bcm56334_a0_dsymbols,
#else
    /* Use the static per-chip symbol tables */
    &bcm56334_a0_symbols,
#endif
#endif

    /* Port map */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
    sizeof(_ports)/sizeof(_ports[0]),
    _ports,
#endif

    /* Variable register array info */
    &bcm56334_a0_numel_info,

    /* Configuration dependent memory max index */
    &bcm56334_a0_mem_maxidx,

};

/* Declare function first to prevent compiler warnings */
extern int
bcm56321_a0_setup(cdk_dev_t *dev);

int
bcm56321_a0_setup(cdk_dev_t *dev)
{
    dev->chip_info = &bcm56321_a0_chip_info;

    return cdk_xgs_setup(dev);
}

