/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * This software is governed by the Broadcom Switch APIs license.
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#include <cdk/chip/bcm56960_a0_defs.h>

/* Block types */
const char *bcm56960_a0_blktype_names[] = {
    "avs",
    "clport",
    "cmic",
    "epipe",
    "ipipe",
    "iproc",
    "lbport",
    "mmu_glb",
    "mmu_sc",
    "mmu_xpe",
    "ser",
    "top",
    "xlport"
};

/* Block structures */
cdk_xgsd_block_t bcm56960_a0_blocks[] = 
{
    { BCM56960_A0_BLKTYPE_CLPORT,       15,   0,   CDK_PBMP_1(0x0000001e) },
    { BCM56960_A0_BLKTYPE_CLPORT,       16,   0,   CDK_PBMP_1(0x000001e0) },
    { BCM56960_A0_BLKTYPE_CLPORT,       17,   0,   CDK_PBMP_1(0x00001e00) },
    { BCM56960_A0_BLKTYPE_CLPORT,       18,   0,   CDK_PBMP_1(0x0001e000) },
    { BCM56960_A0_BLKTYPE_CLPORT,       19,   0,   CDK_PBMP_1(0x001e0000) },
    { BCM56960_A0_BLKTYPE_CLPORT,       20,   0,   CDK_PBMP_1(0x01e00000) },
    { BCM56960_A0_BLKTYPE_CLPORT,       21,   0,   CDK_PBMP_1(0x1e000000) },
    { BCM56960_A0_BLKTYPE_CLPORT,       22,   0,   CDK_PBMP_2(0xe0000000, 0x00000001) },
    { BCM56960_A0_BLKTYPE_CLPORT,       23,   0,   CDK_PBMP_2(0x00000000, 0x0000001e) },
    { BCM56960_A0_BLKTYPE_CLPORT,       24,   0,   CDK_PBMP_2(0x00000000, 0x000001e0) },
    { BCM56960_A0_BLKTYPE_CLPORT,       25,   0,   CDK_PBMP_2(0x00000000, 0x00001e00) },
    { BCM56960_A0_BLKTYPE_CLPORT,       26,   0,   CDK_PBMP_2(0x00000000, 0x0001e000) },
    { BCM56960_A0_BLKTYPE_CLPORT,       27,   0,   CDK_PBMP_2(0x00000000, 0x001e0000) },
    { BCM56960_A0_BLKTYPE_CLPORT,       28,   0,   CDK_PBMP_2(0x00000000, 0x01e00000) },
    { BCM56960_A0_BLKTYPE_CLPORT,       29,   0,   CDK_PBMP_2(0x00000000, 0x1e000000) },
    { BCM56960_A0_BLKTYPE_CLPORT,       30,   0,   CDK_PBMP_3(0x00000000, 0xe0000000, 0x00000001) },
    { BCM56960_A0_BLKTYPE_CLPORT,       31,   0,   CDK_PBMP_3(0x00000000, 0x00000000, 0x0000001e) },
    { BCM56960_A0_BLKTYPE_CLPORT,       32,   0,   CDK_PBMP_3(0x00000000, 0x00000000, 0x000001e0) },
    { BCM56960_A0_BLKTYPE_CLPORT,       33,   0,   CDK_PBMP_3(0x00000000, 0x00000000, 0x00001e00) },
    { BCM56960_A0_BLKTYPE_CLPORT,       34,   0,   CDK_PBMP_3(0x00000000, 0x00000000, 0x0001e000) },
    { BCM56960_A0_BLKTYPE_CLPORT,       35,   0,   CDK_PBMP_3(0x00000000, 0x00000000, 0x001e0000) },
    { BCM56960_A0_BLKTYPE_CLPORT,       36,   0,   CDK_PBMP_3(0x00000000, 0x00000000, 0x01e00000) },
    { BCM56960_A0_BLKTYPE_CLPORT,       37,   0,   CDK_PBMP_3(0x00000000, 0x00000000, 0x1e000000) },
    { BCM56960_A0_BLKTYPE_CLPORT,       38,   0,   CDK_PBMP_4(0x00000000, 0x00000000, 0xe0000000, 0x00000001) },
    { BCM56960_A0_BLKTYPE_CLPORT,       39,   0,   CDK_PBMP_4(0x00000000, 0x00000000, 0x00000000, 0x0000001e) },
    { BCM56960_A0_BLKTYPE_CLPORT,       40,   0,   CDK_PBMP_4(0x00000000, 0x00000000, 0x00000000, 0x000001e0) },
    { BCM56960_A0_BLKTYPE_CLPORT,       41,   0,   CDK_PBMP_4(0x00000000, 0x00000000, 0x00000000, 0x00001e00) },
    { BCM56960_A0_BLKTYPE_CLPORT,       42,   0,   CDK_PBMP_4(0x00000000, 0x00000000, 0x00000000, 0x0001e000) },
    { BCM56960_A0_BLKTYPE_CLPORT,       43,   0,   CDK_PBMP_4(0x00000000, 0x00000000, 0x00000000, 0x001e0000) },
    { BCM56960_A0_BLKTYPE_CLPORT,       44,   0,   CDK_PBMP_4(0x00000000, 0x00000000, 0x00000000, 0x01e00000) },
    { BCM56960_A0_BLKTYPE_CLPORT,       45,   0,   CDK_PBMP_4(0x00000000, 0x00000000, 0x00000000, 0x1e000000) },
    { BCM56960_A0_BLKTYPE_CLPORT,       46,   0,   CDK_PBMP_5(0x00000000, 0x00000000, 0x00000000, 0xe0000000, 0x00000001) },
    { BCM56960_A0_BLKTYPE_CLPORT,       55,   0,   CDK_PBMP_1(0x00000000) },
    { BCM56960_A0_BLKTYPE_LBPORT,       54,   0,   CDK_PBMP_5(0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000010) },
    { BCM56960_A0_BLKTYPE_LBPORT,       51,   0,   CDK_PBMP_5(0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000020) },
    { BCM56960_A0_BLKTYPE_LBPORT,       52,   0,   CDK_PBMP_5(0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000040) },
    { BCM56960_A0_BLKTYPE_LBPORT,       53,   0,   CDK_PBMP_5(0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000080) },
    { BCM56960_A0_BLKTYPE_XLPORT,       11,   0,   CDK_PBMP_5(0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x0000000e) },
    { BCM56960_A0_BLKTYPE_IPIPE,         1,   1,   CDK_PBMP_5(0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0x000000ff) },
    { BCM56960_A0_BLKTYPE_EPIPE,         2,   1,   CDK_PBMP_5(0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0x000000ff) },
    { BCM56960_A0_BLKTYPE_MMU_XPE,       3,   2,   CDK_PBMP_5(0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0x000000ff) },
    { BCM56960_A0_BLKTYPE_MMU_SC,        4,   2,   CDK_PBMP_5(0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0x000000ff) },
    { BCM56960_A0_BLKTYPE_MMU_GLB,       5,   2,   CDK_PBMP_5(0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0x000000ff) },
    { BCM56960_A0_BLKTYPE_TOP,           7,   0,   CDK_PBMP_5(0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0x000000ff) },
    { BCM56960_A0_BLKTYPE_SER,           8,   0,   CDK_PBMP_5(0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0x000000ff) },
    { BCM56960_A0_BLKTYPE_IPROC,        10,   0,   CDK_PBMP_5(0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0x000000ff) },
    { BCM56960_A0_BLKTYPE_AVS,          59,   0,   CDK_PBMP_5(0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0x000000ff) }
};

/* Symbol table */
#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
extern cdk_symbols_t bcm56960_a0_dsymbols;
#else
extern cdk_symbols_t bcm56960_a0_symbols;
#endif
#endif

/* Physical port numbers */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
static cdk_port_map_port_t _ports[] = {
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
};
#endif

/* Declare function first to prevent compiler warnings */
extern uint32_t
bcm56960_a0_pipe_info(uint32_t addr, int acctype, int blktype, int baseidx);

uint32_t
bcm56960_a0_pipe_info(uint32_t addr, int acctype, int blktype, int baseidx)
{
    int base_type = CDK_XGSD_ADDR2BASETYPE(addr);
    int num_inst = 0;
    int sect_shft = 0;
    uint32_t inst_mask = 0;

    /* Base types */
#define BT_IPORT        0
#define BT_EPORT        1
#define BT_IPIPE        2
#define BT_EPIPE        3
#define BT_CHIP         4
#define BT_XPE          5
#define BT_SLICE        6
#define BT_LAYER        7

    /* Access types */
#define AT_DUPLICATE    9
#define AT_SINGLE       20
#define AT_UNIQUE       31

    /* Per-pipe memory section size */
#define SECT_SHFT_32K   15

#define MMUPORT_IN_PIPE(_m, _p) \
    (((_m) >= ((_p) * 64)) && ((_m) < (((_p) * 64) + 34)))
#define MMUPORT_IN_PIPE0(_m) MMUPORT_IN_PIPE(_m, 0)
#define MMUPORT_IN_PIPE1(_m) MMUPORT_IN_PIPE(_m, 1)
#define MMUPORT_IN_PIPE2(_m) MMUPORT_IN_PIPE(_m, 2)
#define MMUPORT_IN_PIPE3(_m) MMUPORT_IN_PIPE(_m, 3)

    if (baseidx < 0) {
        /* Unique block instances */
        if (acctype == AT_UNIQUE) {
            switch (blktype) {
                case BLKTYPE_IPIPE:
                case BLKTYPE_EPIPE:
                case BLKTYPE_MMU_XPE:
                    inst_mask = 0xf;
                    break;
                case BLKTYPE_MMU_SC:
                    inst_mask = 0x3;
                    break;
                default:
                    break;
            }
        }
        /* Basetype instances */
        switch (blktype) {
        case BLKTYPE_MMU_XPE:
        case BLKTYPE_MMU_SC:
        case BLKTYPE_MMU_GLB:
            switch (base_type) {
            case BT_IPORT:
            case BT_EPORT:
                num_inst = 226;
                break;
            case BT_IPIPE:
            case BT_EPIPE:
                num_inst = 4;
                break;
            case BT_CHIP:
                num_inst = 1;
                break;
            case BT_XPE:
                num_inst = 4;
                break;
            case BT_SLICE:
            case BT_LAYER:
                num_inst = 2;
                break;
            default:
                break;
            }
            break;
        default:
            break;
        }
        /* Section size */
        switch (blktype) {
        case BLKTYPE_MMU_XPE:
            switch (base_type) {
            case BT_XPE:
                if (acctype == AT_SINGLE) {
                    sect_shft = SECT_SHFT_32K;
                }
                break;
            case BT_IPIPE:
            case BT_EPIPE:
            case BT_SLICE:
            case BT_LAYER:
                if (acctype == AT_UNIQUE || acctype == AT_DUPLICATE) {
                    sect_shft = SECT_SHFT_32K;
                }
                break;
            default:
                break;
            }
            break;
        case BLKTYPE_MMU_SC:
            switch (base_type) {
            case BT_EPIPE:
            case BT_XPE:
                if (acctype == AT_SINGLE) {
                    sect_shft = SECT_SHFT_32K;
                }
                break;
            case BT_SLICE:
                if (acctype == AT_SINGLE) {
                    sect_shft = SECT_SHFT_32K;
                }
                break;
            case BT_IPIPE:
            case BT_LAYER:
                if (acctype == AT_UNIQUE || acctype == AT_DUPLICATE) {
                    sect_shft = SECT_SHFT_32K;
                }
                break;
            default:
                break;
            }
            break;
        case BLKTYPE_MMU_GLB:
            switch (base_type) {
            case BT_IPIPE:
            case BT_EPIPE:
            case BT_XPE:
            case BT_SLICE:
            case BT_LAYER:
                if (acctype == AT_SINGLE) {
                    sect_shft = SECT_SHFT_32K;
                }
                break;
            default:
                break;
            }
            break;
        }
        return (sect_shft << 16) | (num_inst << 8) | inst_mask;
    }

    /* Valid unique block instances for specific baseidx */
    inst_mask = 0;

    if (blktype == BLKTYPE_MMU_XPE) {
        switch (base_type) {
        case BT_IPORT:
            if (MMUPORT_IN_PIPE0(baseidx) ||
                MMUPORT_IN_PIPE3(baseidx)) {
                inst_mask = 0x3;
            }
            if (MMUPORT_IN_PIPE1(baseidx) ||
                MMUPORT_IN_PIPE2(baseidx)) {
                inst_mask = 0xc;
            }
            break;
        case BT_EPORT:
            if (MMUPORT_IN_PIPE0(baseidx) ||
                MMUPORT_IN_PIPE1(baseidx)) {
                inst_mask = 0x5;
            }
            if (MMUPORT_IN_PIPE2(baseidx) ||
                MMUPORT_IN_PIPE3(baseidx)) {
                inst_mask = 0xa;
            }
            break;
        case BT_IPIPE:
            if (baseidx == 0 || baseidx == 3) {
                inst_mask = 0x3;
            }
            if (baseidx == 1 || baseidx == 2) {
                inst_mask = 0xc;
            }
            break;
        case BT_EPIPE:
            if (baseidx == 0 || baseidx == 1) {
                inst_mask = 0x5;
            }
            if (baseidx == 2 || baseidx == 3) {
                inst_mask = 0xa;
            }
            break;
        case BT_XPE:
            if (baseidx < 4) {
                inst_mask = (1 << baseidx);
            }
            break;
        case BT_SLICE:
            if (baseidx == 0) {
                inst_mask = 0x5;
            }
            if (baseidx == 1) {
                inst_mask = 0xa;
            }
            break;
        case BT_LAYER:
            if (baseidx == 0) {
                inst_mask = 0x3;
            }
            if (baseidx == 1) {
                inst_mask = 0xc;
            }
            break;
        default:
            break;
        }
    } else if (blktype == BLKTYPE_MMU_SC) {
        switch (base_type) {
        case BT_IPORT:
            if (MMUPORT_IN_PIPE0(baseidx) ||
                MMUPORT_IN_PIPE1(baseidx) ||
                MMUPORT_IN_PIPE2(baseidx) ||
                MMUPORT_IN_PIPE3(baseidx)) {
                inst_mask = 0x3;
            }
            break;
        case BT_IPIPE:
            if (baseidx < 4) {
                inst_mask = 0x3;
            }
            break;
        case BT_SLICE:
            if (baseidx < 2) {
                inst_mask = (1 << baseidx);
            }
            break;
        case BT_LAYER:
            if (baseidx < 2) {
                inst_mask = 0x3;
            }
            break;
        default:
            break;
        }
    }

    return inst_mask;
}

/* Index ranges for this chip */
static cdk_xgsd_numel_range_t _numel_ranges[] = {
    {  0,  0, CDK_PBMP_5(0xffffffff, 0x00000000, 0xffffffff, 0x00000000, 0x000000ff) }, /*  0 */
    {  0,  0, CDK_PBMP_5(0xffffffff, 0x00000003, 0xffffffff, 0x00000003, 0x000000ff) }, /*  1 */
    {  0,  3, CDK_PBMP_5(0xffffffff, 0x00000003, 0xffffffff, 0x00000003, 0x000000ff) }, /*  2 */
    {  0,  1, CDK_PBMP_5(0xffffffff, 0x00000003, 0xffffffff, 0x00000003, 0x000000ff) }  /*  3 */
};

/* Register array encodings for this chip */
static cdk_xgsd_numel_encoding_t _numel_encodings[] = {
    { { 5 } },
    { {  0, -1 } },
    { {  1, -1 } },
    { {  2, -1 } },
    { {  3, -1 } }
};

/* Variable register array info */
cdk_xgsd_numel_info_t bcm56960_a0_numel_info = {
    _numel_ranges,
    _numel_encodings
};

/* Chip information structure */
static cdk_xgsd_chip_info_t bcm56960_a0_chip_info = {

    /* CMIC block */
    BCM56960_A0_CMIC_BLOCK,

    /* CMC instance */
    0,

    /* Other (non-CMIC) block types */
    13,
    bcm56960_a0_blktype_names,

    /* Address calculation */
    NULL,

    /* Other (non-CMIC) blocks */
    47,
    bcm56960_a0_blocks,

    /* Valid ports for this chip */
    CDK_PBMP_5(0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0x000000fb),

    /* Chip flags */
    CDK_XGSD_CHIP_FLAG_IPROC |
    0,

#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
    /* Use regenerated symbol tables from the DSYM program */
    &bcm56960_a0_dsymbols,
#else
    /* Use the static per-chip symbol tables */
    &bcm56960_a0_symbols,
#endif
#endif

    /* Port map */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
    sizeof(_ports)/sizeof(_ports[0]),
    _ports,
#endif

    /* Variable register array info */
    &bcm56960_a0_numel_info,

    /* Configuration dependent memory max index */
    NULL,

    /* Pipe info */
    bcm56960_a0_pipe_info,

};

/* Declare function first to prevent compiler warnings */
extern int
bcm56960_a0_setup(cdk_dev_t *dev);

int
bcm56960_a0_setup(cdk_dev_t *dev)
{
    dev->chip_info = &bcm56960_a0_chip_info;

    return cdk_xgsd_setup(dev);
}

