/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * This software is governed by the Broadcom Switch APIs license.
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#include <cdk/chip/bcm56640_a0_defs.h>

/* Block types */
const char *bcm56640_a0_blktype_names[] = {
    "axp",
    "clport",
    "cmic",
    "epipe",
    "etu",
    "ibod",
    "ipipe",
    "ism",
    "mmu",
    "top",
    "xlport",
    "xtport"
};

/* Block structures */
cdk_xgsm_block_t bcm56640_a0_blocks[] = 
{
    { BCM56640_A0_BLKTYPE_CLPORT,       13,   0,   CDK_PBMP_3(0x00000000, 0xffe00000, 0x00000001) },
    { BCM56640_A0_BLKTYPE_CLPORT,       15,   0,   CDK_PBMP_3(0x00000000, 0x00000000, 0x0001ffe0) },
    { BCM56640_A0_BLKTYPE_XLPORT,       11,   0,   CDK_PBMP_2(0x00000000, 0x000001e0) },
    { BCM56640_A0_BLKTYPE_XLPORT,       14,   0,   CDK_PBMP_3(0x00000000, 0x00000000, 0x0000001e) },
    { BCM56640_A0_BLKTYPE_XTPORT,        8,   0,   CDK_PBMP_1(0x00001ffe) },
    { BCM56640_A0_BLKTYPE_XTPORT,        9,   0,   CDK_PBMP_1(0x01ffe000) },
    { BCM56640_A0_BLKTYPE_XTPORT,       10,   0,   CDK_PBMP_2(0xfe000000, 0x0000001f) },
    { BCM56640_A0_BLKTYPE_XTPORT,       12,   0,   CDK_PBMP_2(0x00000000, 0x001ffe00) },
    { BCM56640_A0_BLKTYPE_IPIPE,         1,   1,   CDK_PBMP_2(0xffffffff, 0x7fffffff) },
    { BCM56640_A0_BLKTYPE_EPIPE,         2,   1,   CDK_PBMP_2(0xffffffff, 0x7fffffff) },
    { BCM56640_A0_BLKTYPE_MMU,           3,   2,   CDK_PBMP_2(0xffffffff, 0x7fffffff) },
    { BCM56640_A0_BLKTYPE_AXP,           4,   0,   CDK_PBMP_3(0x00000000, 0x00000000, 0x003e0000) },
    { BCM56640_A0_BLKTYPE_TOP,           6,   0,   CDK_PBMP_3(0xffffffff, 0xffffffff, 0x003fffff) },
    { BCM56640_A0_BLKTYPE_ISM,          16,   1,   CDK_PBMP_2(0xffffffff, 0x7fffffff) },
    { BCM56640_A0_BLKTYPE_ETU,          17,   0,   CDK_PBMP_3(0xffffffff, 0xffffffff, 0x003fffff) },
    { BCM56640_A0_BLKTYPE_IBOD,         18,   0,   CDK_PBMP_3(0xffffffff, 0xffffffff, 0x003fffff) }
};

/* Symbol table */
#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
extern cdk_symbols_t bcm56640_a0_dsymbols;
#else
extern cdk_symbols_t bcm56640_a0_symbols;
#endif
#endif

/* Physical port numbers */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
static cdk_port_map_port_t _ports[] = {
    0, 37, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80
};
#endif

/* Index ranges for this chip */
static cdk_xgsm_numel_range_t _numel_ranges[] = {
    {  0,  0, CDK_PBMP_2(0xffffffff, 0x77ffffff)             }, /*  0 */
    {  0,  0, CDK_PBMP_2(0x00000000, 0x00110000)             }, /*  1 */
    {  0, 19, CDK_PBMP_2(0x00000000, 0x00110000)             }, /*  2 */
    {  0,  9, CDK_PBMP_2(0x00000000, 0x00110000)             }, /*  3 */
    {  0,  9, CDK_PBMP_2(0x00000000, 0x0000ff00)             }, /*  4 */
    {  0,  7, CDK_PBMP_2(0x00000000, 0x0000000f)             }, /*  5 */
    {  0,  7, CDK_PBMP_2(0x00000000, 0x000000f0)             }, /*  6 */
    {  0,  9, CDK_PBMP_2(0x00000000, 0x00ff0000)             }, /*  7 */
    {  0,  7, CDK_PBMP_2(0x00000000, 0x01000000)             }, /*  8 */
    {  0, 47, CDK_PBMP_2(0x00000000, 0x08000000)             }, /*  9 */
    {  0,  7, CDK_PBMP_2(0x00000000, 0x04000000)             }, /* 10 */
    {  0,  0, CDK_PBMP_2(0xffffffff, 0x7dffffff)             }, /* 11 */
    {  0,  3, CDK_PBMP_2(0xffffffff, 0x7dffffff)             }, /* 12 */
    {  1,  7, CDK_PBMP_2(0xffffffff, 0x1dffffff)             }, /* 13 */
    {  8,  9, CDK_PBMP_2(0x00000000, 0x08ffff00)             }, /* 14 */
    { 10, 47, CDK_PBMP_2(0x00000000, 0x08000000)             }, /* 15 */
    {  0,  0, CDK_PBMP_2(0xffffffff, 0x3dffffff)             }, /* 16 */
    {  0,  0, CDK_PBMP_2(0xffffffff, 0x35ffffff)             }  /* 17 */
};

/* Register array encodings for this chip */
static cdk_xgsm_numel_encoding_t _numel_encodings[] = {
    { { 17 } },
    { {  0, -1 } },
    { {  1, -1 } },
    { {  2, -1 } },
    { {  3, -1 } },
    { {  4, -1 } },
    { {  5, -1 } },
    { {  6, -1 } },
    { {  7, -1 } },
    { {  8, -1 } },
    { {  9, -1 } },
    { { 10, -1 } },
    { { 11, -1 } },
    { { 12, -1 } },
    { { 11, 13, 14, 15, -1 } },
    { { 16, 13, 14, 15, -1 } },
    { { 17, -1 } }
};

/* Variable register array info */
cdk_xgsm_numel_info_t bcm56640_a0_numel_info = {
    _numel_ranges,
    _numel_encodings
};

/* Chip information structure */
static cdk_xgsm_chip_info_t bcm56640_a0_chip_info = {

    /* CMIC block */
    BCM56640_A0_CMIC_BLOCK,

    /* CMC instance */
    0,

    /* Other (non-CMIC) block types */
    12,
    bcm56640_a0_blktype_names,

    /* Address calculation */
    NULL,

    /* Other (non-CMIC) blocks */
    16,
    bcm56640_a0_blocks,

    /* Valid ports for this chip */
    CDK_PBMP_3(0x00000001, 0xffe00020, 0x003fffe1),

    /* Chip flags */
    BCM56640_A0_CHIP_FLAG_BW260G |
    0,

#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
    /* Use regenerated symbol tables from the DSYM program */
    &bcm56640_a0_dsymbols,
#else
    /* Use the static per-chip symbol tables */
    &bcm56640_a0_symbols,
#endif
#endif

    /* Port map */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
    sizeof(_ports)/sizeof(_ports[0]),
    _ports,
#endif

    /* Variable register array info */
    &bcm56640_a0_numel_info,

    /* Configuration dependent memory max index */
    NULL,

};

/* Declare function first to prevent compiler warnings */
extern int
bcm56640_a0_setup(cdk_dev_t *dev);

int
bcm56640_a0_setup(cdk_dev_t *dev)
{
    dev->chip_info = &bcm56640_a0_chip_info;

    return cdk_xgsm_setup(dev);
}

