# $Id: 4862e1c7f956bb5255811322266d02156990ec6a $ Broadcom SDK $
# This software is governed by the Broadcom Switch APIs license.
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = shared
LIBNAME = libbmdshared

include $(CDK)/make/lib.mk
