# $Id: 1bee9c4168a4ad4a53f6c0d147978b0b37e5ca6b $ Broadcom SDK $
# This software is governed by the Broadcom Switch APIs license.
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = api
LIBNAME = libbmdapi

include $(CDK)/make/lib.mk
