/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * This software is governed by the Broadcom Switch APIs license.
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#include <cdk/chip/bcm56560_a0_defs.h>

/* Block types */
const char *bcm56560_a0_blktype_names[] = {
    "avs",
    "bcport",
    "clport",
    "cmic",
    "cxxport",
    "epipe",
    "ipipe",
    "iproc",
    "lbport",
    "mmu",
    "pgw_cl",
    "rdb",
    "ser",
    "top",
    "xlport",
    "xlportb"
};

/* Block structures */
cdk_xgsd_block_t bcm56560_a0_blocks[] = 
{
    { BCM56560_A0_BLKTYPE_BCPORT,       37,   0,   CDK_PBMP_1(0x00000000) },
    { BCM56560_A0_BLKTYPE_BCPORT,       38,   0,   CDK_PBMP_1(0x00000000) },
    { BCM56560_A0_BLKTYPE_CLPORT,       15,   0,   CDK_PBMP_1(0x00020000) },
    { BCM56560_A0_BLKTYPE_CLPORT,       17,   0,   CDK_PBMP_2(0xe0000000, 0x00000001) },
    { BCM56560_A0_BLKTYPE_CLPORT,       18,   0,   CDK_PBMP_2(0x00000000, 0x0000001e) },
    { BCM56560_A0_BLKTYPE_CLPORT,       26,   0,   CDK_PBMP_2(0x00000000, 0x00200000) },
    { BCM56560_A0_BLKTYPE_CLPORT,       28,   0,   CDK_PBMP_3(0x00000000, 0x00000000, 0x0000001e) },
    { BCM56560_A0_BLKTYPE_CLPORT,       29,   0,   CDK_PBMP_3(0x00000000, 0x00000000, 0x000001e0) },
    { BCM56560_A0_BLKTYPE_CXXPORT,      16,   0,   CDK_PBMP_1(0x00020000) },
    { BCM56560_A0_BLKTYPE_CXXPORT,      27,   0,   CDK_PBMP_2(0x00000000, 0x00200000) },
    { BCM56560_A0_BLKTYPE_LBPORT,       30,   0,   CDK_PBMP_3(0x00000000, 0x00000000, 0x00000200) },
    { BCM56560_A0_BLKTYPE_XLPORT,       12,   0,   CDK_PBMP_1(0x001e0000) },
    { BCM56560_A0_BLKTYPE_XLPORT,       13,   0,   CDK_PBMP_1(0x01e00000) },
    { BCM56560_A0_BLKTYPE_XLPORT,       14,   0,   CDK_PBMP_1(0x1e000000) },
    { BCM56560_A0_BLKTYPE_XLPORT,       23,   0,   CDK_PBMP_2(0x00000000, 0x01e00000) },
    { BCM56560_A0_BLKTYPE_XLPORT,       24,   0,   CDK_PBMP_2(0x00000000, 0x1e000000) },
    { BCM56560_A0_BLKTYPE_XLPORT,       25,   0,   CDK_PBMP_3(0x00000000, 0xe0000000, 0x00000001) },
    { BCM56560_A0_BLKTYPE_XLPORTB,      10,   0,   CDK_PBMP_1(0x00001e00) },
    { BCM56560_A0_BLKTYPE_XLPORTB,      21,   0,   CDK_PBMP_2(0x00000000, 0x0001e000) },
    { BCM56560_A0_BLKTYPE_XLPORTB,       8,   0,   CDK_PBMP_1(0x0000001e) },
    { BCM56560_A0_BLKTYPE_XLPORTB,      19,   0,   CDK_PBMP_2(0x00000000, 0x000001e0) },
    { BCM56560_A0_BLKTYPE_XLPORTB,      22,   0,   CDK_PBMP_2(0x00000000, 0x001e0000) },
    { BCM56560_A0_BLKTYPE_XLPORTB,       9,   0,   CDK_PBMP_1(0x000001e0) },
    { BCM56560_A0_BLKTYPE_XLPORTB,      20,   0,   CDK_PBMP_2(0x00000000, 0x00001e00) },
    { BCM56560_A0_BLKTYPE_XLPORTB,      11,   0,   CDK_PBMP_1(0x0001e000) },
    { BCM56560_A0_BLKTYPE_IPIPE,         1,   1,   CDK_PBMP_3(0xffffffff, 0xffffffff, 0x000007ff) },
    { BCM56560_A0_BLKTYPE_EPIPE,         2,   1,   CDK_PBMP_3(0xffffffff, 0xffffffff, 0x000007ff) },
    { BCM56560_A0_BLKTYPE_MMU,           3,   2,   CDK_PBMP_3(0xffffffff, 0xffffffff, 0x000007ff) },
    { BCM56560_A0_BLKTYPE_PGW_CL,        6,   0,   CDK_PBMP_2(0xfffffffe, 0x0000001f) },
    { BCM56560_A0_BLKTYPE_PGW_CL,        7,   0,   CDK_PBMP_3(0x00000000, 0xffffffe0, 0x000001ff) },
    { BCM56560_A0_BLKTYPE_TOP,          31,   0,   CDK_PBMP_3(0xffffffff, 0xffffffff, 0x000007ff) },
    { BCM56560_A0_BLKTYPE_SER,          32,   0,   CDK_PBMP_3(0xffffffff, 0xffffffff, 0x000007ff) },
    { BCM56560_A0_BLKTYPE_AVS,          33,   0,   CDK_PBMP_3(0xffffffff, 0xffffffff, 0x000007ff) },
    { BCM56560_A0_BLKTYPE_IPROC,        34,   0,   CDK_PBMP_3(0xffffffff, 0xffffffff, 0x000007ff) },
    { BCM56560_A0_BLKTYPE_RDB,          36,   0,   CDK_PBMP_3(0x00000000, 0x00000000, 0x00000400) }
};

/* Symbol table */
#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
extern cdk_symbols_t bcm56560_a0_dsymbols;
#else
extern cdk_symbols_t bcm56560_a0_symbols;
#endif
#endif

/* Physical port numbers */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
static cdk_port_map_port_t _ports[] = {
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72
};
#endif

/* Index ranges for this chip */
static cdk_xgsd_numel_range_t _numel_ranges[] = {
    {  0,  0, CDK_PBMP_3(0xffffffff, 0xffffffff, 0x000007ff) }, /*  0 */
    {  0,  0, CDK_PBMP_3(0xffffffff, 0xffffffff, 0x000003ff) }, /*  1 */
    {  0,  0, CDK_PBMP_1(0x0000ffff)                         }, /*  2 */
    {  0,  4, CDK_PBMP_1(0x0000ffff)                         }, /*  3 */
    {  0,  9, CDK_PBMP_1(0x0000ffff)                         }, /*  4 */
    {  0,  3, CDK_PBMP_3(0xffffffff, 0xffffffff, 0x000003ff) }, /*  5 */
    {  0,  1, CDK_PBMP_3(0xffffffff, 0xffffffff, 0x000007ff) }  /*  6 */
};

/* Register array encodings for this chip */
static cdk_xgsd_numel_encoding_t _numel_encodings[] = {
    { { 8 } },
    { {  0, -1 } },
    { {  1, -1 } },
    { {  2, -1 } },
    { {  3, -1 } },
    { {  4, -1 } },
    { {  5, -1 } },
    { {  6, -1 } }
};

/* Variable register array info */
cdk_xgsd_numel_info_t bcm56560_a0_numel_info = {
    _numel_ranges,
    _numel_encodings
};

/* Chip information structure */
static cdk_xgsd_chip_info_t bcm56560_a0_chip_info = {

    /* CMIC block */
    BCM56560_A0_CMIC_BLOCK,

    /* CMC instance */
    0,

    /* Other (non-CMIC) block types */
    16,
    bcm56560_a0_blktype_names,

    /* Address calculation */
    NULL,

    /* Other (non-CMIC) blocks */
    35,
    bcm56560_a0_blocks,

    /* Valid ports for this chip */
    CDK_PBMP_3(0xffffffff, 0xffffffff, 0x000001ff),

    /* Chip flags */
    CDK_XGSD_CHIP_FLAG_IPROC |
    BCM56560_A0_CHIP_FLAG_FREQ793 |
    0,

#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
    /* Use regenerated symbol tables from the DSYM program */
    &bcm56560_a0_dsymbols,
#else
    /* Use the static per-chip symbol tables */
    &bcm56560_a0_symbols,
#endif
#endif

    /* Port map */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
    sizeof(_ports)/sizeof(_ports[0]),
    _ports,
#endif

    /* Variable register array info */
    &bcm56560_a0_numel_info,

    /* Configuration dependent memory max index */
    NULL,

    /* Pipe info */
    NULL,

};

/* Declare function first to prevent compiler warnings */
extern int
bcm56560_a0_setup(cdk_dev_t *dev);

int
bcm56560_a0_setup(cdk_dev_t *dev)
{
    dev->chip_info = &bcm56560_a0_chip_info;

    return cdk_xgsd_setup(dev);
}

