# $Id: 171e7b8978d8efc9a7fcf49d967451703373a43f $ Broadcom SDK $
# This software is governed by the Broadcom Switch APIs license.
# This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
# 
# Copyright 2007-2020 Broadcom Inc. All rights reserved.
#

LOCALDIR = libc
LIBNAME = libcdklibc

include $(CDK)/make/lib.mk

