/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * This software is governed by the Broadcom Switch APIs license.
 * This license is set out in https://raw.githubusercontent.com/Broadcom-Network-Switching-Software/OpenMDK/master/Legal/LICENSE file.
 * 
 * Copyright 2007-2020 Broadcom Inc. All rights reserved.
 */

#include <cdk/chip/bcm53242_a0_defs.h>

/* Block types */
const char *bcm53242_a0_blktype_names[] = {
    "cpic",
    "epic",
    "exp",
    "gpic",
    "spi",
    "sys"
};

/* Block structures */
cdk_robo_block_t bcm53242_a0_blocks[] = 
{
    { BCM53242_A0_BLKTYPE_EPIC,       CDK_PBMP_1(0x00ffffff) },
    { BCM53242_A0_BLKTYPE_GPIC,       CDK_PBMP_1(0x06000000) },
    { BCM53242_A0_BLKTYPE_CPIC,       CDK_PBMP_1(0x01000000) },
    { BCM53242_A0_BLKTYPE_EXP,        CDK_PBMP_1(0x07ffffff) },
    { BCM53242_A0_BLKTYPE_SPI,        CDK_PBMP_1(0x07ffffff) },
    { BCM53242_A0_BLKTYPE_SYS,        CDK_PBMP_1(0x07ffffff) }
};

/* Symbol table */
#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
extern cdk_symbols_t bcm53242_a0_dsymbols;
#else
extern cdk_symbols_t bcm53242_a0_symbols;
#endif
#endif

/* Physical port numbers */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
static cdk_port_map_port_t _ports[] = {
    24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 26
};
#endif

/* Declare function first to prevent compiler warnings */
extern uint32_t
bcm53242_a0_blockport_addr(int port, int size, uint32_t offset);

uint32_t
bcm53242_a0_blockport_addr(int port, int size, uint32_t offset)
{
    if (port < 0) {
        port = 0;
    }
    if ((offset & 0xff00) == 0x6800 ||  /* MIB */
        (offset & 0xff00) == 0xa000) {  /* FE MII */
        /* Use page size */
        size = 0x100;
    }
    if ((offset & 0xff00) == 0xb900) {  /* SerDes GMII */
        /* Use page size */
        size = 0x100;
        /* First GE port is 25 */
        port -= 25;
    }
    if ((offset & 0xff00) == 0xd800) {  /* EXT GMII */
        /* Use page size */
        size = 0x100;
        /* First port is CPIC port (24) */
        port -= 24;
    }
    port -= (offset >> 16);
    return (offset & 0xffff) + (port * size); 
}

/* Chip information structure */
static cdk_robo_chip_info_t bcm53242_a0_chip_info = {

    /* Block types */
    6,
    bcm53242_a0_blktype_names,

    /* Address calculation */
    bcm53242_a0_blockport_addr,

    /* Chip blocks */
    6,
    bcm53242_a0_blocks,

    /* Valid ports for this chip */
    CDK_PBMP_1(0x07ffffff),

    /* Chip flags */
    0,

#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
#if CDK_CONFIG_CHIP_SYMBOLS_USE_DSYMS == 1
    &bcm53242_a0_dsymbols,
#else
    &bcm53242_a0_symbols,
#endif
#endif

    /* Port map */
#if CDK_CONFIG_INCLUDE_PORT_MAP == 1
    sizeof(_ports)/sizeof(_ports[0]),
    _ports,
#endif

};

/* Declare function first to prevent compiler warnings */
extern int
bcm53242_a0_setup(cdk_dev_t *dev);

int
bcm53242_a0_setup(cdk_dev_t *dev)
{
    dev->chip_info = &bcm53242_a0_chip_info;

    return cdk_robo_setup(dev);
}

